apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-pv-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: web-nginx
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pv-claim  # Sets name of PVC
  labels:
    app: web-nginx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 1Gi  # Sets volume size
  selector:
    matchLabels:
      app: web-nginx