apiVersion: v1
kind: Service
metadata:
  name: web-nginx-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: web-nginx

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webapp-statefulset
spec:
  serviceName: "rqgen" # Service name for the StatefulSet
  replicas: 1 # Number of replicas/pods
  selector:
    matchLabels:
      app: web-nginx # Label for selecting pods
  template:
    metadata:
      labels:
        app: web-nginx # Label for the pods
    spec:
      containers:
      - name: webapp-container
        image: docker.io/olalere1/webappimage10  # Replace with your container image
        ports:
        - containerPort: 80 # Port exposed by the container
        # Add other container specifications as needed
        # volumeMounts, environment variables, etc.
        volumeMounts:
          - mountPath: /app/                  #/var/lib/postgresql/data
            name: webapp-volume
      volumes:
        - name: webapp-volume
          persistentVolumeClaim:
            claimName: webapp-pv-claim # Maps claim from PersistantVolumeClaim
  